### ISSUE TITLE
Unable to specifiy foreign key column name

### ISSUE THREAD

**Issue by chazzka** [multicaret/laravel-acquaintances#100]
The based-upon package [laravel-follow](https://github.com/overtrue/laravel-follow) deals with different config attribute for foreign key (changing the default `"user_id"`). 

This is useful when using different Model for auth (instead of the default `User`)

This package unfortunately omits it, making different foreign key impossible to set, eventually causing errors in autogenerated queries. (interactions.`foreign_key_name`).

Now, if user wants a different foreign key naming, he can directly specify in migration, but later generated scripts will still respect the previous configuration.

Please consider adding similar configuration as in previous package [on this line](https://github.com/overtrue/laravel-follow/blob/7f8ed934d7448b3abbd9e0d3b16f1ceac5b9fd51/src/Traits/Follower.php#L105)

**Comment by adriallongarriu** [comment]
Hello @mkwsra, i was facing this error. With the documentation I thought that just by adding the traits `CanXXX` like `CanLike` it will work with any model. 

- It would be interesting than the interaction table has two morphTo and interactions would work with any model to any model. The friendships table it already works that way.
- On the other hand now on the config has `interactions_user_id_fk_column_name` but is not used in the migration for the interactions table.

For now i directly specify the column name in migration alredy created.

**Comment by mkwsra** [comment]
Hi Adrià, thanks for pointing this out, we have to do something about this (someone of us)

**Comment by adriallongarriu** [comment]
@mkwsra later i will make a PR modifying the migration and the function `isRelationExists` that uses 'user_id' to use the variables in config file.

The option to use two morphTo relation will be cool but will require more time and will introduce breaking changes.
