### ISSUE TITLE
Unknown column issue

### ISSUE THREAD

**Issue by Algeneralo** [multicaret/laravel-acquaintances#15]
Hi, First of all , thanks for this package.
There's a very strange issue when I try to add like, check if the target has been like be auth API user
Here is what I got:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column "interactions.api_auth_id" in "where clause" (SQL: select exists(select * from "topics" inner join "interactions" on "topics"."id" = "interactions"."subject_id" where "interactions"."api_auth_id" = 1 and "interactions"."subject_type" = App\\Models\\Topic and "interactions"."relation" = like and "subject_id" = 1 and "topics"."deleted_at" is null) as "exists")","
`

**Comment by mkwsra** [comment]
Thank you and I appreciate it, but I guess this use care is rare in comparison to the majority of developed Laravel apps, hence, I will leave it for now waiting for any other requests then for sure I will implement such a feature, and thanks!
