### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by bigint** [multicaret/laravel-acquaintances#17]
It would be great if this package update its support to Laravel 8!

**Comment by mkwsra** [comment]
Yes for sure I will do so tomorrow maximum.

**Comment by mkwsra** [comment]
![image](https://user-images.githubusercontent.com/1743919/92649698-16ff6600-f2f4-11ea-8611-f7cb5e29ecf9.png)
I just read the requirements for this package and it was fine, then I installed it on Laravel 8! everything seems to be fine.


Can you please share with me your issue so I can help?

**Comment by bigint** [comment]
Yes this is working fine now @mkwsra 😊!
