### ISSUE TITLE
Error in CanVote.php: str_plural 

### ISSUE THREAD

**Issue by ferrari308guy** [multicaret/laravel-acquaintances#18]
Hello,

Is this package still maintained? If so, I discovered a bug when using this package on Laravel 8. In CanVote.php, there's an error on the following line:

`return Interaction::attachRelations($this, str_plural($type), $targets, $class);`

It looks like the str_plural function is no longer supported in Laravel 8. The str_plural function needs to be updated to Str::plural.

**Comment by mkwsra** [comment]
Hi there,

Yes for sure it's maintained. I will upload this fix. 

Thank you for reporting

**Comment by mkwsra** [comment]
Now it's fixed in v3.4.0, so please give it a try and let me know.

Thanks again!

**Comment by ferrari308guy** [comment]
Works great. Thanks for the quick fix!

**Comment by mkwsra** [comment]
You're welcome
