### ISSUE TITLE
[feature] Watch Later/Saved?

### ISSUE THREAD

**Issue by francoism90** [multicaret/laravel-acquaintances#19]
Thanks for providing this great package. :)

I was thinking of adding saved methods, would you accept this as a PR? A lot of websites offer this feature like FB & Reddit.
This would be very useful when exploring models (posts, books, videos, music, etc.).

If this can be done differently or you think this out of the scope of this package, just let me know.

**Comment by mkwsra** [comment]
Thank you so much for using our package :) 

For sure, you are welcome to make this change!

**Comment by francoism90** [comment]
@mkwsra I'm going to close this PR, sorry. I cannot find the correct terms and I do think likes/favorites may be preferred terms instead. You cannot use terms like `save`/`store`/.. and I don't like the term `watchlist` as this implies 'watching'.

Sorry for the noise, I'll be using the likes for this instead. :)
