### ISSUE TITLE
help with using isFollowedBy within a get()

### ISSUE THREAD

**Issue by jayenne** [multicaret/laravel-acquaintances#20]
Hi,
I'm struggling to get all models where they are followed by the current Auth::user

**my repository is using:**
```
$boards = Board::withCount('posts')
->isFollowedBy($user)
->paginate($this->pagination);
```
the error I get is: `Call to undefined method Illuminate\Database\Eloquent\Builder::isFollowedBy()`

**However, when I try:**
```
$boards = Board::isFollowedBy($user)
->paginate($this->pagination);
```
the error is: ` Non-static method App\Models\Board::isFollowedBy() should not be called statically`

how would I get all models where a user has followed (or subscribed, liked etc.)

**Comment by mkwsra** [comment]
The matter, in fact, is that the function `isFollowedBy()` is made only to check if this user has been following or not; it returns a boolean.

if you wish you can create such a helper function within your Board model:

```php
public function getFollowersFollowedBy($userId)
{
    return $this->followers->filter(function ($follower) use ($userId) {
        return $follower->id == $userId;
    });
}
```

Please let me know if I'm being any help to you.

**Comment by jayenne** [comment]
Thank you for the help Mohamed.
Unfortunately I'm still get ting the same errors.
Would you mind looking at my implementation for a minute please?

I have included a stripped down version of the model, controller & repository [here](https://paste.laravel.io/0f7c0dfd-bc30-4ca9-9cb7-36eee5dfa40a)

**Comment by mkwsra** [comment]
You are welcome Jayenne,

I took a look at your snippets, and simply the helper function I've provided isn't _static_, hence you got the same error,however,

To achieve what you want, simply tweak your `getAll()` function to the following:

```php
$boards = Board::whereHas('followers', function ($query) use ($userId) {
            $query->where('user_id', $userId);
        })->paginate($this->pagination);
```

Let me know what will happen, and I'm here to help :)

**Comment by jayenne** [comment]
that's perfect, thank you Mohamed.
