### ISSUE TITLE
Show the posts of the current user and following users.

### ISSUE THREAD

**Issue by ArtMin96** [multicaret/laravel-acquaintances#22]
How can I show the posts of the following users? I have a table of posts I want to be displayed in the posts of the active user and his followers. Thanks.

**Comment by mkwsra** [comment]
Hi there Arthur,

I didn't fully grasp what you're asking about here, but what I got it (and correct me if I'm wrong)

A "users show view" (AKA active user) and you displayed his posts, however, now you want to display the posts of his/hers followers?

**Comment by ArtMin96** [comment]
Thanks for the reply. Yes. You right.

**Comment by ArtMin96** [comment]
Any news?

**Comment by mkwsra** [comment]
I will look at it today and let you know. Sorry for being late.

**Comment by ArtMin96** [comment]
Not a problem. Thank you so much.

**Comment by mkwsra** [comment]
// foreach for active user posts

// The followers of this user.
```php
foreach($user->followers as $follower){
   foreach($follower->posts){
      //
   }
}
```

Do you mean something like this?

If you want me to be helpful please provide some code snippets so I can fully understand the issue

**Comment by ArtMin96** [comment]
Thanks for the answer.

I have a livewire component for the post.

```php

<?php

namespace App\Http\Livewire\Post;

use Illuminate\Support\Facades\Auth;
use Livewire\Component;
use App\Models\Post;

class PostCard extends Component
{

    public $user;

    protected $listeners = ['rerenderPost' => '$refresh'];

    public function render()
    {
        $posts = Post::where('user_id', $this->user->id)
            ->orderBy('created_at', 'DESC')
            ->paginate(5);

        return view('livewire.post.post-card', ['posts' => $posts, 'user' => $this->user]);
    }
}
```

```php
<div>
    @if(!$posts->isEmpty())
        @foreach($posts as $post)
            <livewire:post.single-post :post="$post" :user="$user" :key="$post->id" />
        @endforeach
    @else
        <div class="flex justify-center mt-10">
            <p class="text-lg font-semibold text-gray-500">{{ __('title.empty_post') }} - {{ config('app.name') }}</p>
        </div>
    @endif
</div>
```

I want to display the current user and his following user's posts ordering by created date. Like Facebook feed page.

**Comment by ArtMin96** [comment]
Do you think this is the right option?

```php
$id = $this->user->id;
        $posts = Post::whereIn('user_id', function($query) use ($id)
        {
            $query->select('subject_id')
                ->from('interactions')
                ->where('user_id', $id);
        })->orWhere('user_id', $id)
            ->orderBy('created_at', 'DESC')
            ->paginate(5);
```
