### ISSUE TITLE
How to paginate followers?

### ISSUE THREAD

**Issue by mayhemant** [multicaret/laravel-acquaintances#24]
I tried with

```php
$this->user->followers->paginate(10);
```

But throws

```
Method Illuminate\Database\Eloquent\Collection::paginate does not exist.
```

**Comment by faustbrian** [comment]
You need to paginate the query builder with `$this->user->followers()->paginate(10);`

**Comment by mayhemant** [comment]
Thanks, @faustbrian, The pagination works but the `links()` seems like not working!

Here is the result https://taskord.com/@filip/followers

**Comment by mayhemant** [comment]
Oops it seems like working fine when logged out, but now while logged in! This must be issue with some other component!

Thanks for assisting @faustbrian! I'm closing this now!
