### ISSUE TITLE
Like: Reaction type support.

### ISSUE THREAD

**Issue by ArtMin96** [multicaret/laravel-acquaintances#26]
Is there any way I can give the reaction type of 'like'? Like on Facebook.

Ex. $user->like($targets, 'reaction');
Reaction types: 'Like', 'Love', 'Haha'...

**Comment by mkwsra** [comment]
Unfortunately, It's not supported for now and I do think we will add it anytime soon, however, you may take advantage of the column `interactions.relation_value`, but if you chose to do so then you will be using your own storing and retrieving methods.

**Comment by ArtMin96** [comment]
Thanks for the quick response. Can you say in which case you use ```interactions.relation_value``` column?

**Comment by mkwsra** [comment]
Yeah for sure, it's being used only for storing the rating value, so I guess you are good to go :)

**Comment by ArtMin96** [comment]
Thank you so much. Your repo is helped me a lot.
