### ISSUE TITLE
Error: Trait method ratings has not been applied, because there are collisions with other trait methods on App\Models\User

### ISSUE THREAD

**Issue by mohan-nishit** [multicaret/laravel-acquaintances#29]
When starting with a fresh install of Laravel 8.28.1 (using `laravel new my-project`) along with an install of jetstream (with Livewire, with/without teams), adding the Traits to the default User class results in the error: Trait method ratings has not been applied, because there are collisions with other trait methods on App\Models\User
![image](https://user-images.githubusercontent.com/8962159/108743076-7083e600-755e-11eb-9923-e4a244efbcef.png)

**Comment by mohan-nishit** [comment]
Also tried this with Laravel Breeze, and it seems to work fine.

**Comment by mkwsra** [comment]
Based on your screenshot, you are using the `CanRate` trait, hence your User model will have a function called `ratings` and this is conflicting with something within your code, perhaps you can help me out in figuring it out and I would be more than happy to help.

Please open back the issue whenever you get a lead on this
