### ISSUE TITLE
Unknown column 'updated_at'

### ISSUE THREAD

**Issue by RJFares** [multicaret/laravel-acquaintances#38]
Upgrading to 3.4.3 introduced 2 issues:

Method getFullModelName not found (I checked the pull request which fixes it correctly).
But the other pending issue is 
```
Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `interactions` (`subject_id`, `user_id`, `created_at`, `subject_type`, `relation`
, `updated_at`) values (1, 5, 2021-03-17 10:33:16, App\Models\Comment, upvote, 2021-03-17 10:33:16))
```

whenever I call the upvote() method.

**Comment by RJFares** [comment]
The migration stub may have to be updated.
I have manually changed the migration of interactions_table to remove the 'created_at' and set $table->timestamps() instead

**Comment by mkwsra** [comment]
Cool, thank you so much, would you care to make a PR for this fix?

**Comment by RJFares** [comment]
I never did PRs, I'll try now :)

**Comment by mkwsra** [comment]
Don't worry about it it's easy and intuitive, go ahead with it 😃

**Comment by RJFares** [comment]
Added PR: https://github.com/multicaret/laravel-acquaintances/pull/39

**Comment by harlacher** [comment]
Appreciate the updates & PRs but: these are backwards-incompatible changes and break existing installations. Please either add new migrations and alter the table schema(s) to provide a full upgrade path or, bump the major version. Thanks!

**Comment by RJFares** [comment]
@harlacher a previous discussion was made concerning naming of db migrations and should be resolved for future updates if @mkwsra makes the change
