### ISSUE TITLE
Type of Illuminate\Database\Eloquent\Relations\Pivot::$incrementing must be bool

### ISSUE THREAD

**Issue by ArtMin96** [multicaret/laravel-acquaintances#45]
Hi. When I call the methods in CanBeViewed trait it returns this error.

**Type of Illuminate\Database\Eloquent\Relations\Pivot::$incrementing must be bool (as in class Illuminate\Database\Eloquent\Model)**

Laravel v8.12
PHP v7.4

**Comment by ArtMin96** [comment]
In the case of other classes, it returns the same error. I think this problem is caused by PHP type. This problem has never arisen before.

**Comment by mkwsra** [comment]
@gowl If you can help since I'm super busy, that would be great

**Comment by ArtMin96** [comment]
Is there any news?
