### ISSUE TITLE
Usage with livewire and notifications

### ISSUE THREAD

**Issue by NielsvanHoof** [multicaret/laravel-acquaintances#49]
Hey, Users in my app can send friend requests to other users, When they click the add friend button I would like to notify the user that got send the friend request a notification. But how would I go using the package together with Livewire to send a notification when a user gets a friend request. Is their any build in functionality for usage with livewire ?

**Comment by ArtMin96** [comment]
add-friend.blade.php

`<div>
    <button wire:click="friendRequest" wire:loading.attr="disabled" class="flex items-center rounded-lg p-3 font-semibold text-blue-600 bg-blue-100 transition duration-300 ease-in-out hover:bg-blue-200 focus:outline-none">
        <x-icons.feathericons.user-plus class="w-5 h-5 mr-2" />
        {{ __('button.add_friend') }}
    </button>
</div>`

AddFriend.php

`class AddFriend extends Component
{

    /**
     * @var User $user
     */
    public User $user;

    public function mount($user)
    {
        $this->user = $user;
    }

    /**
     * Send friend request to user.
     */
    public function friendRequest()
    {
        if (auth()->check()) {
            if (auth()->user()->is($this->user->id)) {
                $this->emit('show-toast', __('messages.cant_request_yourself'), 'default');
            } else {
                DB::transaction(function () {
                    auth()->user()->befriend($this->user);

                    if (!auth()->user()->isFollowing($this->user)) {
                        auth()->user()->follow($this->user);
                    }

                    if (auth()->user()->hasSentFriendRequestTo($this->user)) {
                        Notification::send($this->user, new FriendRequest(auth()->user()));
                    }
                });

                $this->emit('renderInteractionButtons');
            }
        } else {
            abort(403);
        }
    }

    /**
     * Render the component.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function render()
    {
        return view('livewire.user.interaction-buttons.add-friend');
    }
}`

**Comment by NielsvanHoof** [comment]
Yea this got me a good start, thank you !
