### ISSUE TITLE
Can we eager load the friend/follower/favorite count?

### ISSUE THREAD

**Issue by sawirricardo** [multicaret/laravel-acquaintances#52]
Hi, @mkwsra , first of all, thank you for bringing this package to the community. We are grateful for your contribution.

One thing I want to ask can we eager load it? Because right now, when we load the models in tremondous amount, the queries start to get crazy 😅.

Here are the screenshot of the queries. 104 queries happened for each model.
<img width="619" alt="Screen Shot 2021-05-18 at 20 26 44" src="https://user-images.githubusercontent.com/37329575/118659480-8c262200-b817-11eb-840d-209d62f4f795.png">

**Comment by mkwsra** [comment]
You are welcome, and I'm so sorry for late reply, 

For sure you can eager load them depending on the relation name: for example:

```
->with('followers');

// or in your case
->with('favoriters');

**Comment by sawirricardo** [comment]
Hi @mkwsra Oh, nice 👍🏻. I think it would be more nice if we can add it to the readme.md?
