### ISSUE TITLE
A blocked user can unlock himself

### ISSUE THREAD

**Issue by pyrou** [multicaret/laravel-acquaintances#54]
Current implementation of `acceptFriendRequest` doesn't check the status of existing friendship between users.
This is a serious security issue if developper not aware of this behavior and simply implement controller that maps 1 to 1 acquaintances methods.

```php
// Let's create two friends
[$user, $friend] = User::factory(2)->create();
$user->befriend($friend);
$friend->acceptFriendRequest($user);
$this->assertTrue($user->isFriendWith($friend)); // OK 

// Things goes bad, user blocks friend
$user->blockFriend($friend);
$this->assertFalse($user->isFriendWith($friend)); // OK
        
// Later.. malicious friend perform an acceptFriendRequest
$friend->acceptFriendRequest($user);
$this->assertFalse($user->isFriendWith($friend)); // Failed asserting that true is false.
```

As `befriend()` method check for precondition (it calls canBefriend()), we would expect from `acceptFriendRequest` the same level of verification.

**Comment by mkwsra** [comment]
Can you please help me and test this small tweak by updating the source code of the library itself? 

Like the shown image, just add the following if:
```php
        if ($recipient->hasBlocked($this)) {
            return false;
        }
```
In the following location: `src/Traits/Friendable.php:95:9`


The final result must be like this image:
![image](https://user-images.githubusercontent.com/1743919/138163367-b206c11d-22c3-4ca5-b35e-3e46a9d299bb.png)


I will be working on a different project but I am online with you, let me know please

**Comment by mkwsra** [comment]
Please open it again anytime you wisha
