### ISSUE TITLE
Method Illuminate\Database\Eloquent\Collection::whereRecipient does not exist.

### ISSUE THREAD

**Issue by micos7** [multicaret/laravel-acquaintances#56]
I have in a controller ,both current_user and friend have the expected users.
```
        $current_user = Auth::user();
        $friend = User::findOrFail($friend_id);

        if(!$current_user->isBlockedBy($friend)){
```
It fails in the if condition with the message 

Method Illuminate\Database\Eloquent\Collection::whereRecipient does not exist.

Below is the method in the Friendable trait,what is strange that it used to work. I have the lastest version (3.5.3),Laravel 7
```
public function hasBlocked(Model $recipient)
    {
        return $this->friends()->whereRecipient($recipient)->whereStatus(Status::BLOCKED)->exists();
    }
```
Thanks.

**Comment by mkwsra** [comment]
It's strange indeed, because the migration left untouched, can you change the last code snippet to the following and let me know if it works:

```
return $this->friends()->where('recipient_id',$recipient)->whereStatus(Status::BLOCKED)->exists();
```

And send only the friend id like the following snippet:
```
if(!$current_user->isBlockedBy($friend_id)){
```

**Comment by micos7** [comment]
More bizarre behaviour:
If I replace $this-friends() with its implementation it works.
```
        $a = Interaction::getFriendshipModelName();
        return $this->morphMany($a, 'sender')->whereRecipient($recipient)->whereStatus(Status::BLOCKED)->exists();
```

**Comment by micos7** [comment]
I`m an idiot,I had a friends() relation on the User,apparently they conflicted.

**Comment by mkwsra** [comment]
Don't worry and I'm glad its solved now :)
