### ISSUE TITLE
{{ $model->likers()->count() }}  Eager ?

### ISSUE THREAD

**Issue by f4xy** [multicaret/laravel-acquaintances#68]
Models/Thread.php
`
class Thread extends Model
{
    use HasFactory;

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable')->whereNull('parent_id');
    }

}
`

Models/Comment.php
`
class Comment extends Model
{
    use HasFactory, CanBeLiked;

    protected $with = ['user', 'replies'];

    public function commentable()
    {
        return $this->morphTo();
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    //zi
    public function replies()
    {
        return $this->hasMany(Comment::class, 'parent_id')->oldest();
    }

}
`

Livewire/Comments.php
`class Comments extends Component
{
    public $model;

    public function render()
    {

        return view('livewire.comment.comments', [
            'comments' => $this->model
                                ->comments()
                                ->paginate(10)
        ]);
    }
}`

Livewire/comment.php
`
class Comment extends Component
{
    public $comment;

    public function render()
    {
        return view('livewire.comment.comment', [
            'replys' => $this->comment->replies
        ]);
    }
}
`

When I call {{$model - > likers() - > count()}} on the front end, the N + 1 problem occurs.

I use ‘beyondcode/laravel-query-detector’ package to remind me:

<img width="449" alt="截屏2021-09-01 下午10 52 46" src="https://user-images.githubusercontent.com/88174794/131695167-b58d8193-7ac6-488c-a7ab-09d8b9180aa5.png">

and debugbar :

<img width="818" alt="截屏2021-09-01 下午10 53 15" src="https://user-images.githubusercontent.com/88174794/131695833-ce06fd9d-97c2-4616-935a-5263d5f27b9d.png">

Thank you very much for providing such a powerful package, and I hope you can help me. This problem has bothered me for a week, but it still can't be solved. Thank you very much again!

**Comment by mkwsra** [comment]
You are always welcome, 

For sure you can eager load the relations, simply, add the relation you want to, in your case (as far as I understand it) it must be 'likers'

So please add it to your `with` function or attribute of your model

Let me know if it worked or if you need any further help

**Comment by f4xy** [comment]
The problem is not solved.

You may not have noticed, I have already added it.

protected $with = ['user', 'replies', 'likers'] in Models/Comment;

Can you use withCount or morphWithCount in the  package you develop?

The query data is too much, the reason why the EAGER function fails is that I used $model->likers()->count()

**Comment by ronssij** [comment]
`{{ $model - > likers() - > count() }}` this will always cause N + 1 because the `->likers()` is a new relation.

you can always eager load relation couns on you comment model.

eg.
```
$model = $this->model->comments()->withCount(['likers'])->paginate(10);

and so

$item = $model[0]; // model should be looped in your casem this is to very the first item has the likers count
$item->likers_count; // This is not the eage loaded liker count.
```
