### ISSUE TITLE
getPendingsCount() is not in the Friendable trait

### ISSUE THREAD

**Issue by sarik-k** [multicaret/laravel-acquaintances#70]
Documentation says its there but its not.

**Comment by mkwsra** [comment]
Thanks a lot for reporting this, you are totally right, please edit the file `src/Traits/Friendable.php`

And add this function to it:

```php

    /**
     * Get the number of pending requests
     *
     * @param  string  $groupSlug
     *
     * @return integer
     */
    public function getPendingsCount($groupSlug = '')
    {
        $friendsCount = $this->findFriendships(Status::PENDING, $groupSlug)->count();

        return $friendsCount;
    }
```

And I will be adding this function to the library and make a new release soon :) Thanks again for your help

**Comment by sarik-k** [comment]
You're welcome :)

Seems like it calculates for both Incoming and Outgoing requests. I only need the former - how many pending friend requests a user has. 

Doing this in my controller for now: 

```
$count = $request->user()->getFriendRequests()->count();
```

**Comment by mkwsra** [comment]
Awesome, you are already doing it correctly!

And thank you so much for your star, much appreciated 🙏
