### ISSUE TITLE
"Comment" interaction on User/Model ?

### ISSUE THREAD

**Issue by dgillier** [multicaret/laravel-acquaintances#73]
Hi there !

Looks great, I'm wondering if you have plan to add a "Comment" interaction on User/Model ?
Or any suggestion on how to implement this ?

Thanks , Denis

**Comment by mkwsra** [comment]
Honestly, I don't think so, however, if you wish here are some files which will getting up and running with comments functionality with the most requested features with comments, like nested comments and other stuff :)

Comment model is using this library:
[https://github.com/etrepat/baum](https://github.com/etrepat/baum), and if you are facing problem installing it use simply this tutorial :) [https://github.com/etrepat/baum/pull/332](https://github.com/etrepat/baum/pull/332)

[comments.zip](https://github.com/multicaret/laravel-acquaintances/files/7581841/comments.zip)

Steps:
1. Make sure Baum is installed as mentioned
2. Download the zip file and move these 3 files into their own location: Migrations, Models, Traits (if you don't have it create it).
3. In your Post or Article model just add this trait `use Commentable;` it's located in `use App\Traits\Commentable;` see the zip file.

if you face any problem let me know 😃

Cheers,
MK

**Comment by dgillier** [comment]
@mkwsra Great, thanks a lot Mohamed !
