### ISSUE TITLE
Add target type to events

### ISSUE THREAD

**Issue by usernotnull** [multicaret/laravel-acquaintances#75]
When an event is dispatched, and the action sent is by id instead of an eloquent model, there is no way to know what type the model is.

Take cancelVote for example,

In the trait, you have:

```
    public function upvote($targets, $class = __CLASS__)
    {
        Event::dispatch('acq.vote.up', [$this, $targets]);

        return $this->vote($targets, 'upvote', $class);
    }
```

I suggest we add `$class` to the array so that in the listener, we can grab the eloquent model if only the id is sent.

This needs to be applied to all traits in the library. I can open a PR if needed. No breaking change is needed.

Let me know your thoughts.

**Comment by mkwsra** [comment]
Hi John,

Thanks for your comment.
Actually it's a nice idea, and yes why not go ahead and open a PR please, and I will implement it in the upcoming release.

Sorry for the late reply
