### ISSUE TITLE
time limited blocking (suspension)

### ISSUE THREAD

**Issue by jayenne** [multicaret/laravel-acquaintances#77]
Hi, is there a means to have a time limited block so we can suspend / mute / pause a friendship?

A "suspend" trait that accepts a duration that this an auto expiring blocking.
$user->suspend($target,$datetime) // set $datetime of expiry
$user->suspendedUntil($target) // returns datetime of expiry
$user->unsuspend($target) // deletes suspension
$user->hasSuspended($target) // returns bool
$target->isSuspendedBy($user) // returns bool

you get the idea ;)

**Comment by mkwsra** [comment]
Hi Jayenne, It's a great idea actually, not for every scenario but it's really nice to have 🤩

Thank you so much for sharing it and I will plan to implement it in future releases
