### ISSUE TITLE
using within a get where examples?

### ISSUE THREAD

**Issue by jayenne** [multicaret/laravel-acquaintances#78]
Would you have an example snippet of how to get a model (`Post::`) where is/not blocked by the given user (`Auth::user()`) please?

I imagine it may look something like this...
```
$posts = Post::whereNull('p_slug')
            ->orderBy('created_at', 'desc')
            ->where('friends', function ($q) {
                // something here i'm guessing
            })
            ->paginate(20);
```
atm i'm using (but if feels a little cluncky)
```
$blocked = Auth::user()->getBlockedFriendships()->where('recipient_type', 'App\\Models\\Post')->pluck('recipient_id');
$posts = Post::whereNotIn('id', $blocked);
```
Thanks .

**Comment by mkwsra** [comment]
Hi Jayenne, sorry I was really sick,

Yes your example is great, and later on if you are running to many queries you can optimize it but for now (with thousands of users & more thousands of posts) it's the right way:

And if I were you I would only tweak the mentioned code snippet, just by a bit:
```php
$blockedPosts = Auth::user()
               ->getBlockedFriendships()
               ->where('recipient_type', Post::class)
               ->pluck('recipient_id')
               ->toArray();
$posts = Post::whereNotIn('id', $blockedPosts)->get();
```
