### ISSUE TITLE
Disable auto liking by creator of likeable model

### ISSUE THREAD

**Issue by sarik-k** [multicaret/laravel-acquaintances#80]
It seems that when a user creates a likeable model (eg. post), the post gets automatically liked by the user. Is this intended feature? If yes, is there any way I can disable this behavior without manually unliking it upon post creation ?

**Comment by mkwsra** [comment]
Hi Sarik, no there is no such thing so please let me know exactly what are you doing with some code so I can help out, but by default creating a model has nothing to do with calling the `->like()` function

**Comment by sarik-k** [comment]
Its not happening anymore. What I suspect is, yesterday I was creating and deleting a lot of images (likeable model in my app) for testing, so maybe the new ones took the ID's of deleted ones, which were liked by the user previously. Maybe I should remove the likes when deleting an image. Do you think its a possible cause for such behavior? What do you suggest ?
